# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title A Gibbs sampler using Rcpp
#' @description A Gibbs sampler using Rcpp.
#' @param N the number of samples
#' @param thin the number of between-sample random numbers
#' @param a the parameter for gibbsc
#' @param b the parameter for gibbsc
#' @param n the parameter for gibbsc
#' @return a random sample from gibbs \code{mat}
#' @examples
#' \dontrun{
#'     gc <- gibbsC(100, 10, 2, 4, 16)
#'     print(gc)
#' }
#' @export
gibbsC <- function(N, thin, a, b, n) {
    .Call(`_StatComp21039_gibbsC`, N, thin, a, b, n)
}

